### ISSUE TITLE
send all config vars in one request

### ISSUE THREAD

**Issue by bacongobbler** [onbjerg/heroku-to-deis#2]
Hi, just pointing out something:

> Note: Depending on the number of configuration variables, this can take a very long time, as Deis needs to rebuild the application each time.

Note that you can send all of the config variables at once via

```
deis config:set FOO=bar CAR=star
```

So if you can fit that into your script, it'll speed up the migration time significantly :)

Hope this helps

**Comment by onbjerg** [comment]
Yes, I noticed this yesterday, but thanks for pointing it out!
